CREATE DATABASE Locadora;
USE Locadora;

CREATE TABLE Empresa(
	idEmpresa INT PRIMARY KEY IDENTITY,
	nome	 VARCHAR(200) NOT NULL
);

CREATE TABLE Marcas(
	idMarca INT PRIMARY KEY IDENTITY,
	nome  VARCHAR(200) NOT NULL
);

CREATE TABLE Modelo(
	idModelo INT PRIMARY KEY IDENTITY,
	idMarca   INT FOREIGN KEY REFERENCES Marcas (idMarca),
	descricao TEXT NOT NULL
);

CREATE TABLE Veiculo(
	idVeiculo INT PRIMARY KEY IDENTITY,
	idEmpresa   INT FOREIGN KEY REFERENCES Empresa (idEmpresa),
	idModelo   INT FOREIGN KEY REFERENCES Modelo (idModelo),
	placa  TEXT NOT NULL
);

CREATE TABLE Clientes(
	idCliente INT PRIMARY KEY IDENTITY,
	Nome TEXT NOT NULL,
	CPF INT NOT NULL
);

CREATE TABLE Alugueis(
	idAluguel INT PRIMARY KEY IDENTITY,
	idVeiculo   INT FOREIGN KEY REFERENCES Veiculo (idVeiculo),
	idCliente INT FOREIGN KEY REFERENCES Clientes (idCliente),
	dataInicio DATE NOT NULL,
	dataFim DATE NOT NULL, 
);